services:
  db:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=woofy
      - POSTGRESQL_PASSWORD=woofy
      - POSTGRESQL_DATABASE=woofy
      